create table public.notebook_pages (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  notebook_id uuid not null,
  position bigint generated by default as identity,
  paper_style text not null check (
    paper_style in ('blank', 'dotted', 'ruled', 'grid', 'cornell')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (notebook_id, position),
  constraint notebook_pages_notebook_owner_fk
    foreign key (notebook_id, owner_id)
    references public.notebooks(id, owner_id)
    on delete cascade
);

create index notebook_pages_owner_notebook_position_idx
  on public.notebook_pages(owner_id, notebook_id, position);

create trigger notebook_pages_set_updated_at
before update on public.notebook_pages
for each row execute function public.set_updated_at();

alter table public.notebook_pages enable row level security;

create policy notebook_pages_select_own
on public.notebook_pages
for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy notebook_pages_insert_own_active_notebook
on public.notebook_pages
for insert
to authenticated
with check (
  (select auth.uid()) = owner_id
  and exists (
    select 1
    from public.notebooks
    where notebooks.id = notebook_pages.notebook_id
      and notebooks.owner_id = (select auth.uid())
      and notebooks.archived_at is null
  )
);

create policy notebook_pages_update_own_active_notebook
on public.notebook_pages
for update
to authenticated
using ((select auth.uid()) = owner_id)
with check (
  (select auth.uid()) = owner_id
  and exists (
    select 1
    from public.notebooks
    where notebooks.id = notebook_pages.notebook_id
      and notebooks.owner_id = (select auth.uid())
      and notebooks.archived_at is null
  )
);

create policy notebook_pages_delete_own
on public.notebook_pages
for delete
to authenticated
using ((select auth.uid()) = owner_id);

revoke all on public.notebook_pages from anon;
grant select, insert, update, delete on public.notebook_pages to authenticated;
grant usage, select on sequence public.notebook_pages_position_seq to authenticated;
