alter table public.notebook_pages
  add constraint notebook_pages_id_owner_key
  unique (id, owner_id);

create table public.annotations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  notebook_page_id uuid,
  document_id uuid,
  document_page_number integer,
  kind text not null check (
    kind in ('ink', 'highlight')
  ),
  points jsonb not null check (
    jsonb_typeof(points) = 'array'
    and jsonb_array_length(points) between 2 and 4096
  ),
  color text not null check (
    color ~ '^#[0-9a-fA-F]{6}$'
  ),
  width double precision not null check (
    width between 0.0005 and 0.1
  ),
  opacity double precision not null default 1 check (
    opacity between 0 and 1
  ),
  z_index bigint generated by default as identity,
  revision integer not null default 1 check (
    revision > 0
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint annotations_target_check check (
    (
      notebook_page_id is not null
      and document_id is null
      and document_page_number is null
    )
    or
    (
      notebook_page_id is null
      and document_id is not null
      and document_page_number between 1 and 5000
    )
  ),

  constraint annotations_notebook_page_owner_fk
    foreign key (notebook_page_id, owner_id)
    references public.notebook_pages(id, owner_id)
    on delete cascade,

  constraint annotations_document_owner_fk
    foreign key (document_id, owner_id)
    references public.documents(id, owner_id)
    on delete cascade
);

create index annotations_notebook_page_order_idx
  on public.annotations(owner_id, notebook_page_id, z_index)
  where notebook_page_id is not null;

create index annotations_document_page_order_idx
  on public.annotations(
    owner_id,
    document_id,
    document_page_number,
    z_index
  )
  where document_id is not null;

create trigger annotations_set_updated_at
before update on public.annotations
for each row execute function public.set_updated_at();

alter table public.annotations enable row level security;

create policy annotations_select_own
on public.annotations
for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy annotations_insert_own_active_target
on public.annotations
for insert
to authenticated
with check (
  (select auth.uid()) = owner_id
  and (
    (
      notebook_page_id is not null
      and exists (
        select 1
        from public.notebook_pages
        join public.notebooks
          on notebooks.id = notebook_pages.notebook_id
          and notebooks.owner_id = notebook_pages.owner_id
        where notebook_pages.id = annotations.notebook_page_id
          and notebook_pages.owner_id = (select auth.uid())
          and notebooks.archived_at is null
      )
    )
    or
    (
      document_id is not null
      and exists (
        select 1
        from public.documents
        where documents.id = annotations.document_id
          and documents.owner_id = (select auth.uid())
          and documents.source_type = 'pdf'
          and documents.deleted_at is null
      )
    )
  )
);

create policy annotations_update_own_active_target
on public.annotations
for update
to authenticated
using ((select auth.uid()) = owner_id)
with check (
  (select auth.uid()) = owner_id
  and (
    (
      notebook_page_id is not null
      and exists (
        select 1
        from public.notebook_pages
        join public.notebooks
          on notebooks.id = notebook_pages.notebook_id
          and notebooks.owner_id = notebook_pages.owner_id
        where notebook_pages.id = annotations.notebook_page_id
          and notebook_pages.owner_id = (select auth.uid())
          and notebooks.archived_at is null
      )
    )
    or
    (
      document_id is not null
      and exists (
        select 1
        from public.documents
        where documents.id = annotations.document_id
          and documents.owner_id = (select auth.uid())
          and documents.source_type = 'pdf'
          and documents.deleted_at is null
      )
    )
  )
);

create policy annotations_delete_own
on public.annotations
for delete
to authenticated
using ((select auth.uid()) = owner_id);

revoke all on public.annotations from anon;

grant select, insert, update, delete
on public.annotations
to authenticated;

grant usage, select
on sequence public.annotations_z_index_seq
to authenticated;